# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LandProductivityAnalysisTool
                                 A QGIS plugin
 The plugin analyzes and assesses land productivity
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-06-14
        copyright            : (C) 2020 by James Katwere
        email                : katxeus@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'James Katwere'
__date__ = '2020-06-14'
__copyright__ = '(C) 2020 by James Katwere'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LandProductivityAnalysisTool class from file LandProductivityAnalysisTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .land_productivity_analysis_tool import LandProductivityAnalysisToolPlugin
    return LandProductivityAnalysisToolPlugin()
